<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Admin\Resources\ReportLogResource\Pages;
use App\Models\ReportLog;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class ReportLogResource extends Resource
{
    protected static ?string $model = ReportLog::class;
    protected static ?string $navigationIcon = 'heroicon-o-document-chart-bar';
    protected static ?string $navigationGroup = 'Reports';
    protected static ?int $navigationSort = 2;

    public static function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Select::make('scheduled_report_id')->relationship('scheduledReport', 'name')->searchable()->preload(),
            Forms\Components\TextInput::make('report_type')->required()->maxLength(100),
            Forms\Components\Select::make('generated_by')
                ->relationship('generatedBy', 'name')
                ->searchable()
                ->preload()
                ->default(fn () => auth()->id())
                ->disabled()
                ->dehydrated(),
            Forms\Components\Select::make('status')->options(['generating' => 'Generating', 'completed' => 'Completed', 'failed' => 'Failed'])->default('generating')->required(),
            Forms\Components\TextInput::make('file_path')->maxLength(255),
            Forms\Components\DateTimePicker::make('generated_at'),
            Forms\Components\Textarea::make('error_message')->rows(3)->columnSpanFull(),
        ])->columns(2);
    }

    public static function table(Table $table): Table
    {
        return $table->columns([
            Tables\Columns\TextColumn::make('scheduledReport.name')->label('Report'),
            Tables\Columns\TextColumn::make('report_type')->badge(),
            Tables\Columns\TextColumn::make('generatedBy.name')->label('Generated By'),
            Tables\Columns\TextColumn::make('status')->badge()->color(fn ($state) => match ($state) { 'generating' => 'info', 'completed' => 'success', 'failed' => 'danger', default => 'gray' }),
            Tables\Columns\TextColumn::make('generated_at')->dateTime()->sortable(),
        ])
        ->filters([Tables\Filters\SelectFilter::make('status')->options(['generating' => 'Generating', 'completed' => 'Completed', 'failed' => 'Failed'])])
        ->actions([Tables\Actions\EditAction::make()])
        ->bulkActions([Tables\Actions\BulkActionGroup::make([Tables\Actions\DeleteBulkAction::make()])]);
    }

    public static function getRelations(): array
    {
        return [];
    }

    public static function getPages(): array
    {
        return [
            'index'  => Pages\ListReportLogs::route('/'),
            'create' => Pages\CreateReportLog::route('/create'),
            'edit'   => Pages\EditReportLog::route('/{record}/edit'),
        ];
    }
}
